sut:
  image: seegno/node:4-test
  volumes:
    - .:/app
  environment:
    - CI
  links:
    - syscoind
    - syscoind-ssl

syscoind:
  image: willyko/docker-syscoind
  command:
    -printtoconsole
    -regtest=1
    -rest
    -rpcallowip=10.211.0.0/16
    -rpcallowip=172.17.0.0/16
    -rpcallowip=192.168.0.0/16
    -rpcpassword=bar
    -rpcport=18333
    -rpcuser=foo
    -server
  ports:
    - 18333:18333

syscoind-ssl:
  image: willyko/docker-syscoind
  command:
    -printtoconsole
    -regtest=1
    -rest
    -rpcallowip=10.211.0.0/16
    -rpcallowip=172.17.0.0/16
    -rpcallowip=192.168.0.0/16
    -rpcpassword=bar
    -rpcport=18334
    -rpcssl
    -rpcsslcertificatechainfile=/etc/ssl/syscoind/cert.pem
    -rpcsslprivatekeyfile=/etc/ssl/syscoind/key.pem
    -rpcuser=foo
    -server
  volumes:
    - ./test/config/ssl:/etc/ssl/syscoind
  ports:
    - 18334:18334
